[package]
name = "diesel_sample"
version = "0.1.0"
authors = ["takurinton <takurinton@takurinton.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.6", features = ["sqlite"] }
dotenv = "0.15"

[[bin]]
name = "show_posts"
doc = false

[lib]
doc = false